services:
  backend:
    image: backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - external-net
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:postgres@locahost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_APPLICATION_NAME=achievements
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    networks:
      - external-net
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
volumes:
  db-data:

networks:
  external-net:
    external: true